### ISSUE TITLE
sensu-server fails silently with redis 2.8.23, the default version used by AWS elasticache

### ISSUE THREAD

**Issue by dustyketchum** [sensu/sensu-transport#20] opened 2015-11-16 21:37 UTC
hi,

I believe I've determined that sensu-server fails silently with redis 2.8.23, the default version used by AWS elasticache.  You never see the message "i am now the leader" in the logs and sensu fails to do anything useful.  AWS elasticache 2.8.19 works, but unsuspecting AWS users are likely to waste lots of time trying to get sensu to work (I sure did).

thanks,
dusty

**Comment by cwjohnston** [comment] 2016-11-16 01:27
Hi @dustyketchum, thanks for opening this issue. I recognize that you originally opened this a year ago tomorrow(!) but it seems that whatever conditions you may have experienced previously have likely been resolved.

As of today I've been unable to reproduce this issue with the following configuration:
* Sensu Client 0.26.5
* Sensu Enterprise 2.0.0
* AWS Elasticache w/ Redis 2.8.23

FWIW, in the test I conducted I used an Elasticache Redis instance as both the data store and the transport.

I'm going to close this issue but please do let me know if you are still having trouble with Elasticache when using the most recent version of Sensu and I'll be happy to continue investigating.

**Closed by cwjohnston** 2016-11-16 01:27 UTC
Labels: ready
