### ISSUE TITLE
Buildup of RabbitMQ exchanges

### ISSUE THREAD

**Issue by bodgit** [sensu/sensu-transport#53] opened 2017-08-22 15:29 UTC
I have reasonable turnover of Sensu clients as machines are built and torn down and I've noticed on my RabbitMQ server(s) that I get a steady buildup of old `client:*` exchanges after machines have been deleted. Queues seem to be removed as these are marked as auto-delete but I was wondering if there was any particular reason exchanges aren't also declared with auto-delete?

As a workaround it should be fairly trivial for me to enumerate over the list of exchanges and delete any that don't have any bindings which is the telltale sign it's from an old client.

(Of course, the exchanges declared by Sensu are not marked as durable either so a restart of RabbitMQ or a reboot will clear everything out, eventually)

**Comment by majormoses** [comment] 2017-11-01 00:02
https://github.com/sensu/sensu-transport/pull/54

**Comment by annaplotkin** [comment] 2018-08-09 15:32
Closing this issue.

**Closed by annaplotkin** 2018-08-09 15:32 UTC

**Comment by bodgit** [comment] 2018-08-09 15:56
I would say this isn't fixed. #54 would have fixed the issue however that's been dropped in favour of sensu/sensu#1828 which has also been postponed so currently there's no solution.

**Comment by annaplotkin** [comment] 2018-08-09 16:19
Great point @bodgit ! I should have clarified, closing this issue in favor of tracking in 1828 not that the issue is fixed. Happy to re-open if that is preferable.

**Comment by majormoses** [comment] 2018-08-09 21:50
@portertech I think we should reopen this or #54
